### PR TITLE
Get info from members with LEFT JOIN

### PR DESCRIPTION
**Pull request by fritzmg**
This change adds the firstname, lastname and gender field to the export, if available in the tl_member table. It was a request from [this thread](https://community.contao.org/de/showthread.php?39797-E-Mail-Adressen-aus-Contao-exportieren&p=364354) in the German Contao forum - might be useful in general.

### CODE REVIEW

**Comment by fritzmg** [comment]
Sorry, I had unnecessary spaces in the header line for the CSV. In general these two lines
```php
$output = '';
$output .= '"Firstname", "Lastname", "Gender", "E-mail", "Active"'. "\n" ;
```
could simply be replaced by
```php
$output = '"Firstname","Lastname","Gender","E-mail","Active"'. "\n" ;
```

**Comment by lionel-m** [comment]
@fritzmg Thanks for your contribution !

**Comment by fritzmg** [comment]
No problem :)

I have not much experience with pull requests though, so the last change
```php
$output = '"Firstname","Lastname","Gender","E-mail","Active"'. "\n" ;
```
isn't in it - I guess you need to push that manually.

**Comment by lionel-m** [comment]
It's done. Thanks :)

**Pull request merged**
